# Generated by Django 6.0.4 on 2026-04-21 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='muro.post'),
            preserve_default=False,
        ),
    ]
