# Generated by Django 6.0.4 on 2026-05-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0005_alter_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
